---
abstract: "Helper for Mail::Builder::Simple\r"
author:
  - 'Octavian Rasnita <orasnita@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Helper-Model-Email
requires:
  perl: 5.008_008
version: 0.04
