---
abstract: 'Helper for Mail::Builder::Simple'
author:
  - 'Octavian Rasnita C<orasnita@gmail.com>'
build_requires:
  Catalyst::Runtime: 0
  Test::More: 0
  Test::Pod: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Helper-Model-Email
no_index:
  directory:
    - inc
    - t
requires:
  Mail::Builder::Simple: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
